# Generated by Django 5.2.9 on 2026-02-11 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MenuService', '0002_mealpreparation_product_breakfast_calories_and_more'),
        ('UserService', '0002_comment_rating_commentlunch_rating_user_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед')], max_length=20)),
                ('status', models.CharField(choices=[('ordered', 'Заказано'), ('received', 'Получено'), ('cancelled', 'Отменено')], default='ordered', max_length=20)),
                ('received_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breakfast', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MenuService.breakfast')),
                ('lunch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MenuService.lunch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='UserService.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_type', models.CharField(choices=[('single', 'Одноразовая'), ('subscription', 'Абонемент'), ('subscription_week', 'Абонемент неделя'), ('subscription_month', 'Абонемент месяц'), ('subscription_quarter', 'Абонемент квартал')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('paid', 'Оплачено'), ('cancelled', 'Отменено')], default='pending', max_length=20)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='UserService.user')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(default='г', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Ожидает одобрения'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('ordered', 'Заказано'), ('received', 'Получено')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to='UserService.user')),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'chef'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserService.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('payments', 'Отчет по платежам'), ('attendance', 'Отчет по посещаемости'), ('expenses', 'Отчет по затратам'), ('statistics', 'Статистика питания')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserService.user')),
            ],
        ),
    ]
