# Generated by Django 6.0.2 on 2026-02-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakfast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('first_dish', models.CharField()),
                ('drink', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('soup', models.CharField()),
                ('main', models.CharField()),
                ('salad', models.CharField()),
                ('drink', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('week_day', models.CharField(max_length=100)),
                ('breakfast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morning', to='MenuService.breakfast')),
                ('lunch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afternoon', to='MenuService.lunch')),
            ],
        ),
    ]
