# Generated by Django 5.2.9 on 2026-02-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPreparation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('prepared_time', models.DateTimeField(auto_now_add=True)),
                ('ready_to_serve', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_level', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='breakfast',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='contains_allergens',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='breakfast',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lunch',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lunch',
            name='contains_allergens',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lunch',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='drink',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='breakfast',
            name='first_dish',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='drink',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='main',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='salad',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lunch',
            name='soup',
            field=models.CharField(max_length=255),
        ),
    ]
