# Generated by Django 5.2.9 on 2026-02-11 20:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AddField(
            model_name='commentlunch',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Ученик'), ('chef', 'Повар'), ('admin', 'Администратор')], default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.CharField(choices=[('none', 'Без абонемента'), ('week', 'Неделя (5 дней)'), ('month', 'Месяц'), ('quarter', 'Квартал')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='UserService.user')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=200)),
                ('preference_type', models.CharField(choices=[('like', 'Нравится'), ('dislike', 'Не нравится')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='UserService.user')),
            ],
        ),
    ]
